import { Room } from './room.service';

export const ROOMS: Room[] = [
  {
    id: 1,
    type: 'Suite',
    price: 385,
    capacity: 4,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 2,
    type: 'Suite',
    price: 241,
    capacity: 6,
    breakFast: false,
    dinner: true,
    transportCard: false,
  },
  {
    id: 3,
    type: 'Chambre',
    price: 119,
    capacity: 1,
    breakFast: true,
    dinner: true,
    transportCard: false,
  },
  {
    id: 4,
    type: 'Suite',
    price: 227,
    capacity: 2,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 5,
    type: 'Suite',
    price: 154,
    capacity: 2,
    breakFast: false,
    dinner: true,
    transportCard: false,
  },
  {
    id: 6,
    type: 'Suite',
    price: 241,
    capacity: 3,
    breakFast: false,
    dinner: true,
    transportCard: true,
  },
  {
    id: 7,
    type: 'Chambre',
    price: 104,
    capacity: 1,
    breakFast: true,
    dinner: true,
    transportCard: true,
  },
  {
    id: 8,
    type: 'Chambre',
    price: 121,
    capacity: 5,
    breakFast: true,
    dinner: true,
    transportCard: true,
  },
  {
    id: 9,
    type: 'Chambre',
    price: 114,
    capacity: 2,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 10,
    type: 'Chambre',
    price: 91,
    capacity: 5,
    breakFast: true,
    dinner: false,
    transportCard: false,
  },
  {
    id: 11,
    type: 'Chambre',
    price: 118,
    capacity: 4,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 12,
    type: 'Suite',
    price: 263,
    capacity: 1,
    breakFast: false,
    dinner: false,
    transportCard: true,
  },
  {
    id: 13,
    type: 'Chambre',
    price: 133,
    capacity: 4,
    breakFast: false,
    dinner: true,
    transportCard: false,
  },
  {
    id: 14,
    type: 'Chambre',
    price: 129,
    capacity: 4,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 15,
    type: 'Chambre',
    price: 105,
    capacity: 1,
    breakFast: false,
    dinner: true,
    transportCard: false,
  },
  {
    id: 16,
    type: 'Chambre',
    price: 138,
    capacity: 1,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 17,
    type: 'Chambre',
    price: 102,
    capacity: 2,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 18,
    type: 'Suite',
    price: 187,
    capacity: 2,
    breakFast: true,
    dinner: true,
    transportCard: true,
  },
  {
    id: 19,
    type: 'Suite',
    price: 262,
    capacity: 2,
    breakFast: true,
    dinner: true,
    transportCard: false,
  },
  {
    id: 20,
    type: 'Chambre',
    price: 112,
    capacity: 3,
    breakFast: false,
    dinner: true,
    transportCard: true,
  },
  {
    id: 21,
    type: 'Suite',
    price: 186,
    capacity: 4,
    breakFast: true,
    dinner: false,
    transportCard: false,
  },
  {
    id: 22,
    type: 'Chambre',
    price: 113,
    capacity: 4,
    breakFast: true,
    dinner: true,
    transportCard: false,
  },
  {
    id: 23,
    type: 'Suite',
    price: 314,
    capacity: 4,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 24,
    type: 'Suite',
    price: 294,
    capacity: 2,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 25,
    type: 'Chambre',
    price: 124,
    capacity: 1,
    breakFast: true,
    dinner: false,
    transportCard: false,
  },
  {
    id: 26,
    type: 'Chambre',
    price: 137,
    capacity: 2,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 27,
    type: 'Chambre',
    price: 135,
    capacity: 6,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 28,
    type: 'Suite',
    price: 201,
    capacity: 4,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 29,
    type: 'Chambre',
    price: 92,
    capacity: 4,
    breakFast: true,
    dinner: true,
    transportCard: false,
  },
  {
    id: 30,
    type: 'Suite',
    price: 285,
    capacity: 1,
    breakFast: false,
    dinner: false,
    transportCard: true,
  },
  {
    id: 31,
    type: 'Suite',
    price: 258,
    capacity: 4,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 32,
    type: 'Suite',
    price: 257,
    capacity: 6,
    breakFast: false,
    dinner: true,
    transportCard: false,
  },
  {
    id: 33,
    type: 'Suite',
    price: 151,
    capacity: 5,
    breakFast: true,
    dinner: true,
    transportCard: false,
  },
  {
    id: 34,
    type: 'Suite',
    price: 165,
    capacity: 5,
    breakFast: true,
    dinner: true,
    transportCard: true,
  },
  {
    id: 35,
    type: 'Suite',
    price: 319,
    capacity: 1,
    breakFast: false,
    dinner: false,
    transportCard: true,
  },
  {
    id: 36,
    type: 'Suite',
    price: 198,
    capacity: 3,
    breakFast: false,
    dinner: true,
    transportCard: true,
  },
  {
    id: 37,
    type: 'Suite',
    price: 363,
    capacity: 6,
    breakFast: false,
    dinner: true,
    transportCard: false,
  },
  {
    id: 38,
    type: 'Chambre',
    price: 138,
    capacity: 6,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 39,
    type: 'Suite',
    price: 315,
    capacity: 4,
    breakFast: true,
    dinner: false,
    transportCard: false,
  },
  {
    id: 40,
    type: 'Chambre',
    price: 143,
    capacity: 5,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 41,
    type: 'Suite',
    price: 187,
    capacity: 6,
    breakFast: false,
    dinner: true,
    transportCard: true,
  },
  {
    id: 42,
    type: 'Suite',
    price: 171,
    capacity: 5,
    breakFast: false,
    dinner: true,
    transportCard: true,
  },
  {
    id: 43,
    type: 'Chambre',
    price: 110,
    capacity: 6,
    breakFast: false,
    dinner: true,
    transportCard: false,
  },
  {
    id: 44,
    type: 'Suite',
    price: 270,
    capacity: 6,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 45,
    type: 'Chambre',
    price: 101,
    capacity: 6,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 46,
    type: 'Suite',
    price: 394,
    capacity: 1,
    breakFast: false,
    dinner: false,
    transportCard: true,
  },
  {
    id: 47,
    type: 'Chambre',
    price: 101,
    capacity: 3,
    breakFast: true,
    dinner: false,
    transportCard: false,
  },
  {
    id: 48,
    type: 'Chambre',
    price: 139,
    capacity: 4,
    breakFast: true,
    dinner: true,
    transportCard: false,
  },
  {
    id: 49,
    type: 'Suite',
    price: 236,
    capacity: 5,
    breakFast: true,
    dinner: false,
    transportCard: false,
  },
  {
    id: 50,
    type: 'Suite',
    price: 308,
    capacity: 1,
    breakFast: true,
    dinner: true,
    transportCard: false,
  },
  {
    id: 51,
    type: 'Chambre',
    price: 148,
    capacity: 6,
    breakFast: false,
    dinner: true,
    transportCard: true,
  },
  {
    id: 52,
    type: 'Chambre',
    price: 101,
    capacity: 4,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 53,
    type: 'Suite',
    price: 253,
    capacity: 1,
    breakFast: true,
    dinner: false,
    transportCard: false,
  },
  {
    id: 54,
    type: 'Suite',
    price: 179,
    capacity: 2,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 55,
    type: 'Chambre',
    price: 104,
    capacity: 1,
    breakFast: true,
    dinner: true,
    transportCard: false,
  },
  {
    id: 56,
    type: 'Suite',
    price: 378,
    capacity: 5,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 57,
    type: 'Chambre',
    price: 147,
    capacity: 5,
    breakFast: true,
    dinner: false,
    transportCard: false,
  },
  {
    id: 58,
    type: 'Chambre',
    price: 135,
    capacity: 1,
    breakFast: true,
    dinner: false,
    transportCard: false,
  },
  {
    id: 59,
    type: 'Chambre',
    price: 101,
    capacity: 2,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 60,
    type: 'Chambre',
    price: 93,
    capacity: 4,
    breakFast: false,
    dinner: false,
    transportCard: true,
  },
  {
    id: 61,
    type: 'Suite',
    price: 311,
    capacity: 2,
    breakFast: false,
    dinner: true,
    transportCard: false,
  },
  {
    id: 62,
    type: 'Suite',
    price: 374,
    capacity: 1,
    breakFast: false,
    dinner: true,
    transportCard: true,
  },
  {
    id: 63,
    type: 'Chambre',
    price: 139,
    capacity: 3,
    breakFast: false,
    dinner: true,
    transportCard: false,
  },
  {
    id: 64,
    type: 'Suite',
    price: 274,
    capacity: 3,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 65,
    type: 'Chambre',
    price: 146,
    capacity: 2,
    breakFast: true,
    dinner: true,
    transportCard: true,
  },
  {
    id: 66,
    type: 'Chambre',
    price: 107,
    capacity: 4,
    breakFast: false,
    dinner: true,
    transportCard: false,
  },
  {
    id: 67,
    type: 'Chambre',
    price: 129,
    capacity: 2,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 68,
    type: 'Chambre',
    price: 141,
    capacity: 1,
    breakFast: true,
    dinner: true,
    transportCard: true,
  },
  {
    id: 69,
    type: 'Suite',
    price: 355,
    capacity: 1,
    breakFast: true,
    dinner: true,
    transportCard: true,
  },
  {
    id: 70,
    type: 'Suite',
    price: 306,
    capacity: 1,
    breakFast: true,
    dinner: true,
    transportCard: true,
  },
  {
    id: 71,
    type: 'Chambre',
    price: 121,
    capacity: 1,
    breakFast: false,
    dinner: false,
    transportCard: true,
  },
  {
    id: 72,
    type: 'Chambre',
    price: 100,
    capacity: 2,
    breakFast: false,
    dinner: true,
    transportCard: true,
  },
  {
    id: 73,
    type: 'Suite',
    price: 151,
    capacity: 6,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 74,
    type: 'Chambre',
    price: 112,
    capacity: 4,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 75,
    type: 'Suite',
    price: 343,
    capacity: 6,
    breakFast: false,
    dinner: false,
    transportCard: true,
  },
  {
    id: 76,
    type: 'Chambre',
    price: 85,
    capacity: 5,
    breakFast: true,
    dinner: false,
    transportCard: false,
  },
  {
    id: 77,
    type: 'Chambre',
    price: 97,
    capacity: 4,
    breakFast: false,
    dinner: true,
    transportCard: true,
  },
  {
    id: 78,
    type: 'Chambre',
    price: 90,
    capacity: 2,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 79,
    type: 'Suite',
    price: 296,
    capacity: 3,
    breakFast: false,
    dinner: true,
    transportCard: false,
  },
  {
    id: 80,
    type: 'Suite',
    price: 204,
    capacity: 5,
    breakFast: true,
    dinner: true,
    transportCard: false,
  },
  {
    id: 81,
    type: 'Chambre',
    price: 112,
    capacity: 4,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 82,
    type: 'Chambre',
    price: 123,
    capacity: 6,
    breakFast: true,
    dinner: true,
    transportCard: false,
  },
  {
    id: 83,
    type: 'Chambre',
    price: 116,
    capacity: 6,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 84,
    type: 'Suite',
    price: 325,
    capacity: 1,
    breakFast: true,
    dinner: true,
    transportCard: true,
  },
  {
    id: 85,
    type: 'Suite',
    price: 368,
    capacity: 6,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 86,
    type: 'Suite',
    price: 286,
    capacity: 5,
    breakFast: false,
    dinner: false,
    transportCard: true,
  },
  {
    id: 87,
    type: 'Chambre',
    price: 126,
    capacity: 3,
    breakFast: true,
    dinner: true,
    transportCard: false,
  },
  {
    id: 88,
    type: 'Suite',
    price: 397,
    capacity: 4,
    breakFast: false,
    dinner: true,
    transportCard: true,
  },
  {
    id: 89,
    type: 'Chambre',
    price: 120,
    capacity: 2,
    breakFast: true,
    dinner: false,
    transportCard: false,
  },
  {
    id: 90,
    type: 'Suite',
    price: 201,
    capacity: 4,
    breakFast: false,
    dinner: true,
    transportCard: false,
  },
  {
    id: 91,
    type: 'Suite',
    price: 328,
    capacity: 5,
    breakFast: false,
    dinner: false,
    transportCard: true,
  },
  {
    id: 92,
    type: 'Suite',
    price: 341,
    capacity: 4,
    breakFast: true,
    dinner: false,
    transportCard: true,
  },
  {
    id: 93,
    type: 'Chambre',
    price: 113,
    capacity: 2,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 94,
    type: 'Suite',
    price: 290,
    capacity: 5,
    breakFast: false,
    dinner: false,
    transportCard: true,
  },
  {
    id: 95,
    type: 'Chambre',
    price: 141,
    capacity: 6,
    breakFast: true,
    dinner: true,
    transportCard: false,
  },
  {
    id: 96,
    type: 'Chambre',
    price: 144,
    capacity: 4,
    breakFast: false,
    dinner: false,
    transportCard: false,
  },
  {
    id: 97,
    type: 'Suite',
    price: 273,
    capacity: 2,
    breakFast: true,
    dinner: true,
    transportCard: false,
  },
  {
    id: 98,
    type: 'Suite',
    price: 216,
    capacity: 2,
    breakFast: false,
    dinner: false,
    transportCard: true,
  },
  {
    id: 99,
    type: 'Chambre',
    price: 89,
    capacity: 6,
    breakFast: false,
    dinner: true,
    transportCard: false,
  },
  {
    id: 100,
    type: 'Chambre',
    price: 110,
    capacity: 5,
    breakFast: true,
    dinner: true,
    transportCard: true,
  },
];
