name: Docker Image CI

on:
  push:
    branches: [tests]

jobs:

  Cloud-Run-Deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
        
      - name: Setup gcloud environment
        uses: GoogleCloudPlatform/github-actions@0.1.2
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
       
      - name: Configure docker authentication to GCloud
        run: |
          gcloud auth configure-docker
          
      - name: Go back
        run: |
          cd ..
           
      - name: Build the Docker image
        run: |        
          docker build . --tag gcr.io/hotelparadis/hotel
          
      - name: Publish the Docker image to Google Container Registry
        run: |
          docker push gcr.io/hotelparadis/hotel
      
      - name: Deploy to Cloud Run
        run: |
          gcloud beta run deploy hotel-service --image gcr.io/hotelparadis/hotel
