name: Docker Image CI

on:
  push:
    branches: [tests]

jobs:

  Cloud-Run-Deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
      - name: Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1.2.1
      - name: Deploy service to Cloud Run
        uses: stefda/action-cloud-run@v1.0
        with:    
          # Name of the docker image
          image: gcr.io/hotelparadis/hotel
          # Name of the service in Cloud Run
          service: hotel-service
          # GCP project
          project: hotelparadis
          # GCP region
          region: europe-west1
          # GCP service key with storage and run permissions
          service key: ${{secrets.GCLOUD_AUTH}}
